import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Search, CalendarDays, Settings, ChevronDown, MoreHorizontal, Play, Pause,
  Sparkles, Check, Copy, Share2, Plus, Video, Tag, CheckCircle2,
  LayoutDashboard, Users, X, LogOut, MessageSquareText, Download,
  Mic2, CircleStop, ExternalLink, SlidersHorizontal, ArrowUpRight,
  FileText, Link2, ShieldCheck, Clock3, Bell
} from 'lucide-react';
import './styles.css';
import AuthGate from './AuthGate';
import { supabase, supabaseConfigured } from './lib/supabase';

const captureScript = [
  ['00:00', 'Alex Rivera', 'Thanks everyone. Today we are narrowing the launch plan and assigning clear owners.'],
  ['00:09', 'Jamie Morgan', 'The strongest opportunity is activation. New users should reach their first useful moment faster.'],
  ['00:18', 'Sam Kim', 'I will own the onboarding experiment and share the first prototype by Friday.'],
  ['00:27', 'Alex Rivera', 'Let us make the customer beta the first milestone and review it in the next team sync.']
];

const seedMeetings = [
  { id: 'seed-1', title: 'Q3 Product roadmap', date: 'Today, 10:30 AM', duration: '42 min', people: ['AB', 'JM', 'SK', '+3'], color: '#d9e8ff', accent: '#3878d8', topic: 'Product & strategy', summary: 'The team aligned on a focused Q3 roadmap centered around activation, faster sharing, and the new AI workspace.', highlights: ['Ship the new onboarding flow by July 18', 'Move clip sharing into the core meeting experience', 'Run a customer beta with 12 design partners'], transcript: [['00:00', 'Alex Brown', 'Good morning everyone. Today I want us to leave with a clear Q3 roadmap and owners for every major initiative.'], ['04:18', 'Jamie Morgan', 'The biggest opportunity is activation. The first-time experience still asks people to do too much before they see value.'], ['12:42', 'Sam Kim', 'I can take the lead on the new onboarding flow. We should have a beta ready by the 18th.'], ['21:06', 'Alex Brown', 'Let’s make clip sharing a first-class part of the meeting experience, not a hidden action menu.'], ['34:10', 'Jamie Morgan', 'I’ll set up the customer beta with twelve design partners and bring feedback to the next review.']] },
  { id: 'seed-2', title: 'Design critique — meeting detail', date: 'Yesterday, 2:00 PM', duration: '28 min', people: ['SK', 'AB', '+2'], color: '#f4ddff', accent: '#9c58c7', topic: 'Design', summary: 'Reviewed the meeting detail redesign with emphasis on hierarchy, transcript navigation, and making follow-ups actionable.', highlights: ['Test the new transcript density', 'Add keyboard shortcut documentation', 'Use one primary action per panel'], transcript: [['00:00', 'Sam Kim', 'Let’s start with the new detail view. The goal is to make every important moment one click away.'], ['07:32', 'Alex Brown', 'The transcript feels much easier to scan when the speaker and timestamp stay fixed.'], ['16:20', 'Sam Kim', 'We should make the action items panel feel more alive with clear owners and due dates.']] },
  { id: 'seed-3', title: 'Customer interview — Acme', date: 'Jun 18, 9:00 AM', duration: '51 min', people: ['JR', 'ML', '+4'], color: '#ffe4cc', accent: '#d37c42', topic: 'Research', summary: 'Acme’s operations team shared how they use meeting notes today and where handoffs break down.', highlights: ['Send the workflow prototype to Acme', 'Map the handoff from call to CRM', 'Invite ops lead to the beta'], transcript: [['00:00', 'Jordan Reed', 'Thanks for joining. We’re trying to understand what happens after the meeting ends.'], ['14:06', 'Maya Lee', 'The notes are useful, but the handoff into our CRM is where we lose the thread.'], ['38:51', 'Jordan Reed', 'That’s helpful. We’ll send a workflow prototype next week.']] }
];

function App({ session }) {
  const [meetings, setMeetings] = useState(seedMeetings);
  const [selected, setSelected] = useState(seedMeetings[0]);
  const [view, setView] = useState('Meetings');
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState('Overview');
  const [playing, setPlaying] = useState(false);
  const [toast, setToast] = useState('');
  const [loading, setLoading] = useState(Boolean(supabaseConfigured));
  const [showNew, setShowNew] = useState(false);
  const [showShare, setShowShare] = useState(false);
  const [shareLink, setShareLink] = useState('');
  const [showCalendar, setShowCalendar] = useState(false);
  const [showPricing, setShowPricing] = useState(false);
  const [showCapture, setShowCapture] = useState(false);
  const [capture, setCapture] = useState(null);
  const [commandOpen, setCommandOpen] = useState(false);
  const [calendarConnected, setCalendarConnected] = useState(() => localStorage.getItem('fathom-calendar-connected') === 'true');
  const [autoJoin, setAutoJoin] = useState(() => localStorage.getItem('fathom-auto-join') !== 'false');

  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };

  useEffect(() => {
    let alive = true;
    async function load() {
      if (!supabase || !session?.user) { setLoading(false); return; }
      const { data, error } = await supabase.from('meetings').select('*').order('meeting_date', { ascending: false });
      if (error) { notify('Database unavailable; showing the local demo workspace'); setLoading(false); return; }
      if (!data?.length) {
        const payload = seedMeetings.map((m) => ({ owner_id: session.user.id, title: m.title, topic: m.topic, meeting_date: new Date().toISOString(), duration_seconds: parseInt(m.duration) * 60, summary: m.summary, transcript: m.transcript, action_items: m.highlights.map((text, i) => ({ text, owner: ['Alex', 'Jamie', 'Sam'][i], done: false })), highlights: m.highlights.map((text, i) => ({ time: ['04:18', '12:42', '21:06'][i], text })) }));
        const inserted = await supabase.from('meetings').insert(payload).select('*');
        if (!inserted.error && alive) { const mapped = inserted.data.map(fromDb); setMeetings(mapped); setSelected(mapped[0] || seedMeetings[0]); }
      } else if (alive) { const mapped = data.map(fromDb); setMeetings(mapped); setSelected(mapped[0] || seedMeetings[0]); }
      setLoading(false);
    }
    load();
    return () => { alive = false; };
  }, [session?.user?.id]);

  useEffect(() => {
    if (!capture?.active) return undefined;
    const timer = window.setInterval(() => setCapture((current) => current ? { ...current, seconds: current.seconds + 1 } : current), 1000);
    return () => window.clearInterval(timer);
  }, [capture?.active]);

  useEffect(() => {
    const onKeyDown = (event) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); }
      if (event.key === 'Escape') setCommandOpen(false);
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, []);

  const filtered = useMemo(() => meetings.filter((m) => `${m.title} ${m.topic} ${m.summary} ${(m.transcript || []).flat().join(' ')}`.toLowerCase().includes(query.toLowerCase())), [meetings, query]);

  const saveMeeting = async (m) => {
    if (supabase && session?.user && !String(m.id).startsWith('seed-')) await supabase.from('meetings').update({ action_items: m.actionItems, highlights: m.highlights, summary: m.summary, transcript: m.transcript }).eq('id', m.id);
  };
  const toggleAction = async (index) => {
    const actions = (selected.actionItems || selected.highlights.map((text, i) => ({ text, owner: ['Alex', 'Jamie', 'Sam'][i], done: false }))).map((item, i) => i === index ? { ...item, done: !item.done } : item);
    const updated = { ...selected, actionItems: actions }; setSelected(updated); setMeetings((list) => list.map((m) => m.id === updated.id ? updated : m)); await saveMeeting(updated);
  };
  const addHighlight = async (row) => {
    const updated = { ...selected, highlights: [...(selected.highlights || []), row[2]] };
    setSelected(updated); setMeetings((list) => list.map((m) => m.id === updated.id ? updated : m)); await saveMeeting(updated); notify('Moment added to highlights');
  };
  const createMeeting = async (form) => {
    const local = { id: crypto.randomUUID(), title: form.title, date: 'Just now', duration: '0 min', people: ['AR'], color: '#dce8ff', accent: '#4a70c6', topic: form.topic || 'General', summary: form.summary || 'A new meeting ready for notes and follow-ups.', highlights: form.actionItem ? [form.actionItem] : [], actionItems: form.actionItem ? [{ text: form.actionItem, owner: 'Alex', done: false }] : [], transcript: form.transcript ? [['00:00', 'Alex Rivera', form.transcript]] : [] };
    if (supabase && session?.user) { const { data, error } = await supabase.from('meetings').insert({ owner_id: session.user.id, title: local.title, topic: local.topic, meeting_date: new Date().toISOString(), duration_seconds: 0, summary: local.summary, transcript: local.transcript, action_items: local.actionItems, highlights: [] }).select('*').single(); if (!error) local.id = data.id; }
    setMeetings((list) => [local, ...list]); setSelected(local); setShowNew(false); setView('Meetings'); notify('Meeting added to your library');
  };
  const startCapture = () => { setShowNew(false); setCapture({ active: true, seconds: 0, transcript: [] }); setShowCapture(true); notify('Capture started — demo worker is listening'); };
  const stopCapture = async () => {
    const transcript = captureScript;
    await createMeeting({ title: 'Captured meeting — launch planning', topic: 'Captured call', summary: 'The team aligned on activation, an onboarding experiment, and a customer beta milestone.', transcript: transcript.map((r) => `${r[1]}: ${r[2]}`).join('\n'), actionItem: 'Share the onboarding prototype by Friday' });
    setMeetings((list) => list.map((m) => m.title === 'Captured meeting — launch planning' ? { ...m, transcript, duration: `${Math.max(1, Math.ceil((capture?.seconds || 1) / 60))} min`, highlights: ['Own the onboarding experiment', 'Review the customer beta next week'] } : m));
    setCapture(null); setShowCapture(false); notify('Capture processed: transcript and summary are ready');
  };
  const createShare = async () => {
    const payload = { title: selected.title, topic: selected.topic, date: selected.date, duration: selected.duration, summary: selected.summary, highlights: selected.highlights, transcript: selected.transcript };
    const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(payload)))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    const link = `${window.location.origin}/#shared=${encoded}`; setShareLink(link); setShowShare(true);
    try { await navigator.clipboard.writeText(link); notify('Share link copied'); } catch { notify('Share link ready to copy'); }
  };
  const exportMeeting = () => {
    const content = [`${selected.title}`, `${selected.date} · ${selected.duration}`, '', 'SUMMARY', selected.summary, '', 'ACTION ITEMS', ...(selected.actionItems || selected.highlights.map((text) => ({ text }))).map((a) => `- ${a.text || a}`), '', 'TRANSCRIPT', ...(selected.transcript || []).map(([time, speaker, text]) => `[${time}] ${speaker}: ${text}`)].join('\n');
    const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `${selected.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.txt`; link.click(); URL.revokeObjectURL(url); notify('Meeting notes exported');
  };
  const connectCalendar = () => { setCalendarConnected(true); localStorage.setItem('fathom-calendar-connected', 'true'); setShowCalendar(false); notify('Google Calendar connected'); };
  const toggleAutoJoin = () => { const next = !autoJoin; setAutoJoin(next); localStorage.setItem('fathom-auto-join', String(next)); };
  const selectMeeting = (m) => { setSelected(m); setTab('Overview'); setView('Meetings'); };
  const actionCount = meetings.reduce((n, m) => n + (m.actionItems?.length || m.highlights?.length || 0), 0);

  return <div className="app">
    <aside className="sidebar"><div className="brand"><span className="brandmark">f</span><span>fathom</span></div><button className="new-btn" onClick={() => setShowNew(true)}><Plus size={17}/> New meeting</button>
      <nav><Nav icon={<LayoutDashboard/>} label="Meetings" active={view === 'Meetings'} onClick={() => setView('Meetings')}/><Nav icon={<MessageSquareText/>} label="Ask" active={view === 'Ask'} onClick={() => setView('Ask')}/><Nav icon={<Tag/>} label="Highlights" active={view === 'Highlights'} onClick={() => setView('Highlights')}/><Nav icon={<CheckCircle2/>} label="Action items" active={view === 'Action items'} onClick={() => setView('Action items')} count={actionCount}/></nav>
      <div className="nav-label">WORKSPACE</div><Nav icon={<Users/>} label="My team" onClick={() => notify('Team workspace is ready for collaboration')}/><Nav icon={<Settings/>} label="Settings" active={view === 'Settings'} onClick={() => setView('Settings')}/>
      <div className="sidebar-bottom"><button className="upgrade" onClick={() => setShowPricing(true)}><Sparkles size={16}/><div><strong>Unlock more with Pro</strong><span>Unlimited recordings & AI</span></div><ChevronDown size={15}/></button><div className="user"><div className="avatar dark">{initials(session?.user?.user_metadata?.full_name || 'Alex Rivera')}</div><div><strong>{session?.user?.user_metadata?.full_name || 'Alex Rivera'}</strong><span>{session ? 'Connected workspace' : 'Demo workspace'}</span></div>{session && <button className="logout-btn" onClick={() => supabase.auth.signOut()}><LogOut size={15}/></button>}</div></div>
    </aside>
    <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><ChevronDown size={14}/><span className="muted">{view}</span></div><div className="top-actions"><div className="global-search" onClick={() => setCommandOpen(true)}><Search size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} onFocus={() => setCommandOpen(true)} placeholder="Search meetings..." aria-label="Search meetings"/><kbd>⌘ K</kbd></div><button className="icon-btn" title="Calendar" aria-label="Open calendar" onClick={() => setShowCalendar(true)}><CalendarDays size={18}/></button><button className="icon-btn notification-button" title="Notifications" aria-label="Open notifications" onClick={() => notify('You are all caught up')}><Bell size={17}/><span/></button><div className="avatar">{initials(session?.user?.user_metadata?.full_name || 'Alex Rivera')}</div></div></header>
      {view === 'Meetings' && <MeetingsView meetings={filtered} selected={selected} loading={loading} query={query} calendarConnected={calendarConnected} onCalendar={() => setShowCalendar(true)} onSelect={selectMeeting} tab={tab} setTab={setTab} playing={playing} setPlaying={setPlaying} notify={notify} toggleAction={toggleAction} addHighlight={addHighlight} onShare={createShare} onExport={exportMeeting} onClearSearch={() => setQuery('')}/>} 
      {view === 'Ask' && <AskView meetings={meetings} onSelect={selectMeeting}/>} 
      {view === 'Highlights' && <HighlightsView meetings={meetings} onSelect={selectMeeting}/>} 
      {view === 'Action items' && <ActionItemsView meetings={meetings} onToggle={(m, i) => { setSelected(m); setTab('Overview'); toggleAction(i); }}/>} 
      {view === 'Settings' && <SettingsView session={session} calendarConnected={calendarConnected} autoJoin={autoJoin} onCalendar={() => setShowCalendar(true)} onToggleAutoJoin={toggleAutoJoin} onPricing={() => setShowPricing(true)}/>} 
    </main>
    {toast && <div className="toast" role="status"><Check size={16}/><span>{toast}</span><button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={14}/></button></div>}{showNew && <NewMeetingModal onClose={() => setShowNew(false)} onCreate={createMeeting} onStartCapture={startCapture}/>} {showCapture && <CaptureModal capture={capture} onStop={stopCapture}/>} {showShare && <ShareModal link={shareLink} onClose={() => setShowShare(false)} onCopy={() => navigator.clipboard.writeText(shareLink).then(() => notify('Share link copied'))}/>} {showCalendar && <CalendarModal connected={calendarConnected} autoJoin={autoJoin} onClose={() => setShowCalendar(false)} onConnect={connectCalendar} onToggleAutoJoin={toggleAutoJoin}/>} {showPricing && <PricingModal onClose={() => setShowPricing(false)} onChoose={() => { setShowPricing(false); notify('Pro preview enabled for this workspace'); }}/>} {commandOpen && <CommandPalette query={query} meetings={meetings} onQueryChange={setQuery} onClose={() => setCommandOpen(false)} onSelect={(m) => { selectMeeting(m); setCommandOpen(false); }} onClear={() => { setQuery(''); setCommandOpen(false); }}/>}</div>;
}

function MeetingsView({ meetings, selected, loading, query, calendarConnected, onCalendar, onSelect, tab, setTab, playing, setPlaying, notify, toggleAction, addHighlight, onShare, onExport, onClearSearch }) { return <div className="content"><section className="page-head"><div><p className="eyebrow">{calendarConnected ? 'CALENDAR SYNCED' : 'START WITH YOUR NEXT CALL'}</p><h1>Good morning, Alex <span>✦</span></h1><p className="subhead">{calendarConnected ? 'Your conversations, made useful.' : 'Connect your calendar to make meeting capture automatic.'}</p></div><button className="outline-btn" onClick={onCalendar}><CalendarDays size={16}/> {calendarConnected ? 'Calendar connected' : 'Connect calendar'}</button></section><div className="stats"><Stat label="Meetings this week" value={meetings.length} detail="Synced to workspace"/><Stat label="Hours captured" value="8.4" detail="Across your meetings"/><Stat label="Action items" value={meetings.reduce((n, m) => n + (m.actionItems?.length || m.highlights?.length || 0), 0)} detail="Follow-ups detected"/></div><div className="workspace-grid"><section className="meetings-panel"><div className="section-title"><div><h2>Your meetings</h2><p>{loading ? 'Syncing your workspace…' : query ? `Results for “${query}”` : 'All your conversations in one place'}</p></div><button className="filter-btn"><SlidersHorizontal size={14}/> All meetings <ChevronDown size={15}/></button></div><div className="meeting-list">{meetings.map((m) => <MeetingCard key={m.id} m={m} selected={selected.id === m.id} onClick={() => onSelect(m)}/>)}{!meetings.length && (query ? <EmptySearch query={query} onClear={onClearSearch}/> : <EmptyMeetings onCalendar={onCalendar}/>)}</div></section><section className="detail-panel"><DetailHeader m={selected} onShare={onShare} onExport={onExport}/><div className="tabs">{['Overview', 'Transcript', 'Highlights'].map((t) => <button className={tab === t ? 'active' : ''} onClick={() => setTab(t)} key={t}>{t}{t === 'Highlights' && <b>{selected.highlights.length}</b>}</button>)}</div>{tab === 'Overview' ? <Overview m={selected} playing={playing} setPlaying={setPlaying} notify={notify} toggleAction={toggleAction} onShare={onShare} onExport={onExport}/> : tab === 'Transcript' ? <Transcript m={selected} onHighlight={addHighlight}/> : <Highlights m={selected} onShare={onShare}/>}</section></div></div>; }
function DetailHeader({ m, onShare, onExport }) { return <div className="detail-header"><div className="detail-meta"><StatusBadge status="ready" label="Ready"/><span>{m.date}</span><span>·</span><span>{m.duration}</span></div><div className="detail-actions"><button className="icon-btn" title="Share" aria-label="Share meeting" onClick={onShare}><Share2 size={17}/></button><button className="icon-btn" title="Export" aria-label="Export meeting" onClick={onExport}><Download size={16}/></button><button className="icon-btn" title="More actions" aria-label="More meeting actions"><MoreHorizontal size={18}/></button></div><h2>{m.title}</h2><div className="attendees">{m.people.map((p, i) => <div key={i} className="mini-avatar" style={{ background: i === 0 ? m.color : '#eef0f4', color: i === 0 ? m.accent : '#707684' }}>{p}</div>)}<span>{m.topic}</span></div></div>; }
function StatusBadge({ status, label }) { return <span className={`status-badge status-${status}`}><span className="status-dot"/>{label}</span>; }
function Nav({ icon, label, active, onClick, count }) { return <button className={'nav-item ' + (active ? 'active' : '')} onClick={onClick}>{React.cloneElement(icon, { size: 18 })}<span>{label}</span>{count > 0 && <em>{count}</em>}</button>; }
function Stat({ label, value, detail }) { return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function MeetingCard({ m, selected, onClick }) { return <button className={'meeting-card ' + (selected ? 'selected' : '')} onClick={onClick}><div className="meeting-icon" style={{ background: m.color, color: m.accent }}><Video size={18}/></div><div className="meeting-copy"><strong>{m.title}</strong><span>{m.date} <i>·</i> {m.duration}</span><small>{m.topic}</small></div><div className="people-stack">{m.people.slice(0, 3).map((p, i) => <span key={i}>{p}</span>)}</div><MoreHorizontal size={17} className="more"/></button>; }
function Overview({ m, playing, setPlaying, notify, toggleAction, onShare, onExport }) { const actions = m.actionItems || m.highlights.map((text, i) => ({ text, owner: ['Alex', 'Jamie', 'Sam'][i], done: false })); return <div className="detail-body"><div className="player"><div className="wave">{Array.from({ length: 46 }, (_, i) => <i key={i} style={{ height: `${12 + ((i * 17) % 31)}px` }}/> )}</div><div className="player-row"><button className="play" onClick={() => setPlaying(!playing)}>{playing ? <Pause size={16}/> : <Play size={16} fill="currentColor"/>}</button><span>{playing ? '04:18' : '00:00'} / {m.duration}</span><div className="player-tools"><span>1×</span><button onClick={() => notify('Transcript link copied')}><Copy size={15}/></button><button onClick={onShare}><Share2 size={15}/></button><button onClick={onExport}><Download size={15}/></button></div></div></div><div className="ai-card"><div className="ai-heading"><div className="spark"><Sparkles size={16}/></div><div><strong>AI summary</strong><span>Generated moments ago</span></div><button onClick={() => notify('Summary templates: Executive, Sales, Research')}>Change template <ChevronDown size={14}/></button></div><p>{m.summary}</p><div className="summary-tags"><span>3 key topics</span><span>{m.people.length} speakers</span><span>94% confidence</span></div></div><div className="action-heading"><div><h3>Action items</h3><p>Follow-ups detected in this meeting</p></div><button className="text-btn" onClick={() => notify('Add a follow-up from the New meeting menu')}>+ Add item</button></div><div className="action-list">{actions.slice(0, 5).map((a, i) => <div className="action" key={i}><button className={'check ' + (a.done ? 'done' : '')} onClick={() => toggleAction(i)}><Check size={13}/></button><span className={a.done ? 'completed' : ''}>{a.text || a}</span><em>{a.owner || ['Alex', 'Jamie', 'Sam'][i]}</em></div>)}</div></div>; }
function Transcript({ m, onHighlight }) { return <div className="transcript">{m.transcript.length ? m.transcript.map((row, i) => <div className="transcript-row" key={`${row[0]}-${i}`}><time>{row[0]}</time><div className="transcript-content"><div className="speaker-line"><span className={`speaker-avatar speaker-${i % 6}`}>{initials(row[1])}</span><strong>{row[1]}</strong></div><p>{row[2]}</p><button className="transcript-highlight" onClick={() => onHighlight(row)}><Tag size={13}/> Highlight moment</button></div></div>) : <EmptyTranscript/>}</div>; }
function Highlights({ m, onShare }) { return <div className="highlights">{m.highlights.length ? m.highlights.map((h, i) => <div className="highlight" key={i}><div className="highlight-time">{typeof h === 'object' ? h.time : ['04:18', '12:42', '21:06'][i] || '00:00'}<button onClick={onShare}><Share2 size={14}/></button></div><div><strong>{typeof h === 'object' ? h.text : h}</strong><p>{m.transcript[Math.min(i + 1, m.transcript.length - 1)]?.[2] || m.summary}</p></div></div>) : <div className="empty">No highlights yet. Highlight a transcript moment to keep it handy.</div>}</div>; }

function AskView({ meetings, onSelect }) { const [question, setQuestion] = useState(''); const [asked, setAsked] = useState(''); const answer = useMemo(() => { const words = asked.toLowerCase().split(/\s+/).filter((w) => w.length > 3); const hits = meetings.flatMap((m) => (m.transcript || []).map((r) => ({ m, row: r }))).filter(({ m, row }) => `${m.title} ${m.summary} ${row.join(' ')}`.toLowerCase().includes(words[0] || '___')); return hits.slice(0, 3); }, [asked, meetings]); return <div className="content narrow-page"><section className="page-head"><div><p className="eyebrow">ASK YOUR MEETINGS</p><h1>Your second brain, with receipts.</h1><p className="subhead">Search every conversation and jump back to the exact moment that supports the answer.</p></div></section><div className="ask-hero"><div className="ask-icon"><MessageSquareText size={20}/></div><h2>What do you want to know?</h2><form onSubmit={(e) => { e.preventDefault(); if (question.trim()) setAsked(question.trim()); }}><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Which meetings mention activation or onboarding?"/><button className="new-btn">Ask <ArrowUpRight size={16}/></button></form><div className="ask-suggestions"><button onClick={() => setQuestion('What did we decide about onboarding?')}>Onboarding decisions</button><button onClick={() => setQuestion('What are the customer follow-ups?')}>Customer follow-ups</button><button onClick={() => setQuestion('Who owns the beta?')}>Owners and deadlines</button></div></div>{asked && <div className="ask-results"><div className="answer-card"><div className="answer-label"><Sparkles size={15}/> ANSWER</div><p>{answer.length ? `I found ${answer.length} relevant moment${answer.length === 1 ? '' : 's'} across your meetings. The clearest thread is that the team is prioritizing activation, a faster onboarding path, and a customer beta as the next milestone.` : 'I could not find a matching transcript moment yet. Try onboarding, beta, activation, or CRM.'}</p></div>{answer.map(({ m, row }, i) => <button className="citation" key={`${m.id}-${i}`} onClick={() => onSelect(m)}><span>{row[0]}</span><div><strong>{m.title}</strong><p>{row[2]}</p></div><ExternalLink size={15}/></button>)}</div>}</div>; }
function HighlightsView({ meetings, onSelect }) { const highlights = meetings.flatMap((m) => (m.highlights || []).map((h, i) => ({ m, text: typeof h === 'object' ? h.text : h, time: typeof h === 'object' ? h.time : ['04:18', '12:42', '21:06'][i] || '00:00' }))); return <div className="content narrow-page"><section className="page-head"><div><p className="eyebrow">SAVED MOMENTS</p><h1>Highlights worth revisiting.</h1><p className="subhead">Your best decisions and quotes, collected from every meeting.</p></div></section><div className="collection-grid">{highlights.map((h, i) => <button className="collection-card" key={i} onClick={() => onSelect(h.m)}><span className="collection-time">{h.time}</span><strong>{h.text}</strong><small>{h.m.title} · {h.m.topic}</small></button>)}{!highlights.length && <div className="empty">Highlight a transcript moment to see it here.</div>}</div></div>; }
function ActionItemsView({ meetings, onToggle }) { const items = meetings.flatMap((m) => (m.actionItems || m.highlights.map((text, i) => ({ text, owner: ['Alex', 'Jamie', 'Sam'][i], done: false }))).map((a, i) => ({ ...a, m, index: i }))); return <div className="content narrow-page"><section className="page-head"><div><p className="eyebrow">FOLLOW-UPS</p><h1>Keep momentum after the call.</h1><p className="subhead">One place for every promise made in a meeting.</p></div></section><div className="items-card">{items.map((item, i) => <div className="action wide-action" key={i}><button className={'check ' + (item.done ? 'done' : '')} onClick={() => onToggle(item.m, item.index)}><Check size={13}/></button><div><span className={item.done ? 'completed' : ''}>{item.text}</span><small>{item.m.title} · {item.owner || 'Unassigned'}</small></div><Clock3 size={15}/></div>)}</div></div>; }
function SettingsView({ session, calendarConnected, autoJoin, onCalendar, onToggleAutoJoin, onPricing }) { return <div className="content narrow-page"><section className="page-head"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Make capture feel effortless.</h1><p className="subhead">Control how your meetings arrive, process, and get shared.</p></div></section><div className="settings-grid"><div className="settings-card"><div className="settings-icon"><CalendarDays size={17}/></div><div><h3>Calendar connection</h3><p>{calendarConnected ? 'Google Calendar is connected and ready to watch for calls.' : 'Connect Google Calendar to detect upcoming meetings.'}</p></div><button className="outline-btn" onClick={onCalendar}>{calendarConnected ? 'Manage' : 'Connect'}</button></div><div className="settings-card"><div className="settings-icon"><Mic2 size={17}/></div><div><h3>Automatic capture</h3><p>Start the notetaker automatically when a calendar meeting begins.</p></div><button className={'toggle ' + (autoJoin ? 'on' : '')} onClick={onToggleAutoJoin}><span/></button></div><div className="settings-card"><div className="settings-icon"><ShieldCheck size={17}/></div><div><h3>Privacy defaults</h3><p>New meetings are private to this workspace until you share them.</p></div><span className="settings-status">Private</span></div><div className="settings-card"><div className="settings-icon"><Users size={17}/></div><div><h3>Account</h3><p>{session?.user?.email || 'Demo workspace'} · Individual plan</p></div><button className="outline-btn" onClick={onPricing}>View plans</button></div></div><div className="capture-note"><FileText size={16}/><div><strong>Capture worker status</strong><p>The product loop is wired with a local demo capture worker. Replace it with Recall.ai, Meeting BaaS, or browser-tab capture when you connect a production transcription service.</p></div></div></div>; }

function EmptyMeetings({ onCalendar }) { return <div className="empty empty-illustrated"><div className="empty-art"><CalendarDays size={24}/><span/></div><strong>No meetings yet</strong><p>Connect your calendar and your next conversation will appear here.</p><button className="link-btn" onClick={onCalendar}>Connect calendar <ArrowUpRight size={13}/></button></div>; }
function EmptySearch({ query, onClear }) { return <div className="empty empty-search"><Search size={22}/><strong>No meetings match “{query}”</strong><p>Try another topic, speaker, or meeting title.</p><button className="link-btn" onClick={onClear}>Clear search</button></div>; }
function EmptyTranscript() { return <div className="empty empty-transcript"><div className="empty-wave">{Array.from({ length: 18 }, (_, i) => <i key={i} style={{ height: `${9 + ((i * 7) % 19)}px` }}/> )}</div><strong>Transcribing live…</strong><p>The transcript will appear here as your meeting is processed.</p></div>; }
function CommandPalette({ query, meetings, onQueryChange, onClose, onSelect, onClear }) { const results = meetings.filter((m) => `${m.title} ${m.topic} ${m.summary}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6); return <div className="command-backdrop" onMouseDown={onClose}><div className="command-palette" role="dialog" aria-modal="true" aria-label="Search meetings" onMouseDown={(event) => event.stopPropagation()}><div className="command-input"><Search size={18}/><input autoFocus value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search meetings, topics, and summaries"/><kbd>ESC</kbd></div><div className="command-results">{results.length ? results.map((m) => <button key={m.id} onClick={() => onSelect(m)}><div className="command-icon"><Video size={15}/></div><div><strong>{m.title}</strong><span>{m.topic} · {m.date}</span></div><ArrowUpRight size={15}/></button>) : <div className="command-empty"><Search size={18}/><span>No meetings found</span><button className="link-btn" onClick={onClear}>Clear search</button></div>}</div><div className="command-footer"><span><kbd>↵</kbd> Open meeting</span><span><kbd>ESC</kbd> Close</span></div></div></div>; }

function NewMeetingModal({ onClose, onCreate, onStartCapture }) { const [mode, setMode] = useState('capture'); const [form, setForm] = useState({ title: '', topic: '', summary: '', transcript: '', actionItem: '' }); const update = (key, value) => setForm({ ...form, [key]: value }); return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal wide-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">MEETING INBOX</p><h2>Add a meeting</h2></div><button className="icon-btn" aria-label="Close add meeting dialog" onClick={onClose}><X size={17}/></button></div><div className="modal-tabs"><button className={mode === 'capture' ? 'active' : ''} onClick={() => setMode('capture')}><Mic2 size={14}/> Capture a call</button><button className={mode === 'notes' ? 'active' : ''} onClick={() => setMode('notes')}><FileText size={14}/> Add notes</button></div>{mode === 'capture' ? <div className="capture-start"><div className="capture-orb"><Mic2 size={22}/></div><h3>Start a focused capture</h3><p>For this MVP, the capture worker is simulated so you can experience the complete record → transcript → summary loop without a bot joining a real call.</p><button className="new-btn capture-start-btn" onClick={onStartCapture}><Mic2 size={16}/> Start demo capture</button><small><ShieldCheck size={13}/> No audio leaves this browser in demo mode</small></div> : <><p className="modal-copy">Create a workspace record with notes, transcript, and follow-up data.</p><label className="field-label" htmlFor="meeting-title">Meeting title</label><input id="meeting-title" aria-label="Meeting title" placeholder="e.g. Weekly product sync" value={form.title} onChange={(e) => update('title', e.target.value)}/><label className="field-label" htmlFor="meeting-topic">Topic</label><input id="meeting-topic" aria-label="Topic" placeholder="e.g. Sales, Research" value={form.topic} onChange={(e) => update('topic', e.target.value)}/><label className="field-label" htmlFor="meeting-summary">Summary</label><textarea id="meeting-summary" aria-label="Summary" placeholder="What was decided?" value={form.summary} onChange={(e) => update('summary', e.target.value)}/><label className="field-label" htmlFor="meeting-transcript">Transcript note</label><textarea id="meeting-transcript" aria-label="Transcript note" placeholder="Paste a note or key quote" value={form.transcript} onChange={(e) => update('transcript', e.target.value)}/><label className="field-label" htmlFor="meeting-action">First action item</label><input id="meeting-action" aria-label="First action item" placeholder="e.g. Send the follow-up" value={form.actionItem} onChange={(e) => update('actionItem', e.target.value)}/><div className="modal-actions"><button className="outline-btn" onClick={onClose}>Cancel</button><button className="new-btn" disabled={!form.title} onClick={() => form.title && onCreate(form)}><Plus size={16}/> Create meeting</button></div></>}</div></div>; }
function CaptureModal({ capture, onStop }) { return <div className="modal-backdrop"><div className="modal capture-modal"><div className="capture-live"><span className="recording-dot"/> LIVE CAPTURE</div><h2>Listening to your meeting</h2><p className="modal-copy">Demo capture is creating a speaker-separated transcript. You can stop whenever the conversation is complete.</p><div className="capture-timer">{formatTime(capture?.seconds || 0)}</div><div className="capture-wave">{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ height: `${10 + ((i * 13) % 28)}px` }}/> )}</div><div className="capture-status"><span><Check size={13}/> Speaker labels</span><span><Check size={13}/> Live transcript</span><span><Check size={13}/> Auto-summary</span></div><button className="stop-btn" onClick={onStop}><CircleStop size={17}/> Stop & process meeting</button></div></div>; }
function ShareModal({ link, onClose, onCopy }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">SHARE THIS MEETING</p><h2>Ready to share</h2></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div><div className="share-preview"><Link2 size={18}/><div><strong>Anyone with the link can view</strong><span>Summary, highlights, and transcript</span></div></div><div className="share-field"><input readOnly value={link}/><button className="new-btn" onClick={onCopy}><Copy size={15}/> Copy</button></div><p className="modal-footnote"><ShieldCheck size={14}/> Your workspace data stays private until you create a link.</p></div></div>; }
function CalendarModal({ connected, autoJoin, onClose, onConnect, onToggleAutoJoin }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">CALENDAR SETUP</p><h2>{connected ? 'Calendar is connected' : 'Connect your calendar'}</h2></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div>{connected ? <><div className="connected-card"><div className="google-calendar"><CalendarDays size={20}/></div><div><strong>Google Calendar</strong><span>Connected and watching for meetings</span></div><Check size={18} className="connected-check"/></div><div className="setting-row"><div><strong>Auto-join eligible calls</strong><span>Prepare capture when a meeting link appears on your calendar.</span></div><button className={'toggle ' + (autoJoin ? 'on' : '')} onClick={onToggleAutoJoin}><span/></button></div></> : <><p className="modal-copy">Connect Google Calendar to detect upcoming Zoom, Meet, and Teams calls. We only use event details to prepare your meeting workspace.</p><button className="calendar-connect" onClick={onConnect}><CalendarDays size={18}/> Continue with Google Calendar <ArrowUpRight size={15}/></button><div className="privacy-line"><ShieldCheck size={14}/> You can disconnect at any time from Settings.</div></>}</div></div>; }
function PricingModal({ onClose, onChoose }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal pricing-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">SIMPLE PRICING</p><h2>Choose your pace</h2></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div><div className="price-grid"><div className="price-card"><span>Individual</span><strong>Free</strong><p>For trying the full meeting loop.</p><button className="outline-btn" onClick={onChoose}>Current plan</button><small>10 meetings / month · Summary + Ask</small></div><div className="price-card featured"><span>Pro</span><strong>$12 <small>/ month</small></strong><p>For people who live in meetings.</p><button className="new-btn" onClick={onChoose}>Start Pro preview</button><small>Unlimited capture · Faster processing · Sharing</small></div></div></div></div>; }

function fromDb(row) { return { id: row.id, title: row.title, date: new Date(row.meeting_date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }), duration: row.duration_seconds ? Math.round(row.duration_seconds / 60) + ' min' : '0 min', people: ['AR'], color: '#dce8ff', accent: '#4a70c6', topic: row.topic || 'General', summary: row.summary || '', transcript: row.transcript || [], highlights: (row.highlights || []).map((h) => typeof h === 'string' ? h : h.text), actionItems: row.action_items || [] }; }
function initials(name) { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); }
function formatTime(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }

createRoot(document.getElementById('root')).render(<AuthGate><App/></AuthGate>);
